version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:14.5-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  data:
    driver: local

networks:
  app-net:
    driver: bridge
